version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12
    environment:
      - MEILI_MASTER_KEY=masterKey
    ports:
      - '7700:7700'
    volumes:
      - meili_data:/meili_data
    restart: always

  # backend:
  #   build: ./backend
  #   ports:
  #     - '8000:8000'
  #   environment:
  #     - MEILI_HOST=http://meilisearch:7700
  #     - MEILI_MASTER_KEY=masterKey
  #   depends_on:
  #     - meilisearch

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend

volumes:
  meili_data:
